In [1]:
# print the numpy version
import numpy as np
print(np.__version__)

1.23.5


In [2]:
# create a 1D array of numbers from 0 to 9
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# create 3x3 matrix written as "True" with boolean data type
arr = np.full((3,3),True, dtype = bool)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
# extract all the odd elements from the array
arr = np.arange(10)
arr[arr%2 == 1]


array([1, 3, 5, 7, 9])

In [5]:
# extract all the even elements from the array
arr = np.arange(10)
arr[arr % 2 == 0]

# we can also do it as 
# arr = np.arange(0,10,2)  mean increment by 2

array([0, 2, 4, 6, 8])

In [6]:
# replace all the odd numbers in arr with -1
arr = np.arange(10)
arr[arr % 2 == 1] = -1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
# how to replace an item of array without changing the original item
arr = np.arange(14)
outarr = np.where(arr % 2 ==1, -1, arr)
print("\n the change list is:\n")
print(outarr)
print("\nthe original list is :")
arr


 the change list is:

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1]

the original list is :


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [8]:
# convert a 1D array to a 2D array with 3 rows
arr =  np.arange(9)
arr.reshape(3,-1)  # the -1 select the numbers of columns by itself


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# how to stack arrays a and b horizontally
a = np.arange(9).reshape(3,-1)
b = np.arange(9).reshape(3,-1)
np.hstack([a,b])




array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [10]:
# creating a kind of pattern
array = np.array([1,2,3,4])
np.r_[np.repeat(array,4), np.tile(array,4)]


array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 1, 2, 3, 4, 1, 2,
       3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [11]:
#  get the common items between a and b
a = np.array([1,3,4,5,8,9,0])
b = np.array([2,6,3,10,11,5])
np.intersect1d(a,b)

array([3, 5])

In [12]:
# how to remove from one array those items that exist in another
a = np.array([1,3,4,5,8,9,0])
b = np.array([2,6,3,10,11,5])

np.setdiff1d(a,b) # this method make a new array from the difference of the two arrays



array([0, 1, 4, 8, 9])

In [13]:
# how to get the positions where the elements of a and b match

a = np.array([1,3,4,8,9,6,3])
b = np.array([2,3,6,5,5,6,0])

np.where(a == b)

(array([1, 5], dtype=int64),)

In [14]:
# get all items between 4 and 9 from the given list
a = np.array([1,3,4,8,9,10,22,34,38])
index = np.where((a>=4) & (a<=9))
a[index]


array([4, 8, 9])

In [15]:
# Q. Convert the function maxx that works on two scalars, to work on two arrays.

def max(x,y):
    if x>=y:
        return x
    else:
        return y
    
max(1,7)

vectorMax = np.vectorize(max, otypes = [int])
a = [2,4,6,9,4,4] 
b = [3,2,8,2,9,9]

vectorMax(a,b)


array([3, 4, 8, 9, 9, 9])

In [40]:
# swap tow columns with each other
arr = np.arange(9).reshape(3,3)
print("the list before swap is :")
print(arr)
print("\n the list after swap is:")
myArr = arr[:, [1,0,2]] # these numbers 0,1 and 2 show the index and and at which number each column should to be print
myArr




the list before swap is :
[[0 1 2]
 [3 4 5]
 [6 7 8]]

 the list after swap is:


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [53]:
# how to swap two rows in a 2d numpy array
arr = np.arange(9).reshape(3,3)
print(arr)
print("\n after swaping the first two rows :\n")
ar = arr[[1,0,2],:]
ar




[[0 1 2]
 [3 4 5]
 [6 7 8]]

 after swaping the first two rows :



array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [61]:
# how to reverse rows of a 2d arrays

arr = np.arange(12).reshape(4,3)
print(arr)
print("after reversing the rows:")
reverseArray = arr[::-1]
reverseArray


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
after reversing the rows:


array([[12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

###### the above code show that first and last rows will interchange and then 2nd and 3rd rows will interchange

In [65]:
# how to reverse the columns of 2d numpy arrays

arr = np.arange(12).reshape(3,4)
print(arr)
print("\n after reversing columns the array : ")
reverseArr = arr[:,::-1]
reverseArr

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 after reversing columns the array : 


array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

###### same procedure is for columns as for rows  1st column change with last and 2nd with 3rd respectively

In [78]:
# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
import random
rand_arr = np.random.uniform(5,10, size = (5,3))
print(rand_arr)


[[9.38233283 5.8474906  7.41357127]
 [8.1874249  7.9524034  9.28457748]
 [6.20980518 5.50069961 7.39609097]
 [8.57357397 8.70567278 6.41392892]
 [5.93629278 7.12046635 5.40293575]]
